INSERT INTO destination(place, country, population, description, picture_url)
VALUES ('Santorini', 'Greece', 15000.0,
        'Santorini, a stunning Greek island in the Aegean Sea, is renowned for its breathtaking beauty and unique charm. Famous for its iconic blue-domed churches, whitewashed buildings, and picturesque sunsets, Santorini offers a mesmerizing blend of natural wonders and captivating architecture. The island is formed by a volcanic caldera, creating dramatic landscapes and stunning vistas. Visitors can explore the charming villages of Oia, Fira, and Imerovigli, with their narrow winding streets, vibrant bougainvillea-covered buildings, and panoramic views of the sea. Santorini is also known for its pristine beaches, such as the famous Red Beach and Perissa Beach, where crystal-clear turquoise waters meet volcanic black sand. With its romantic ambiance, breathtaking views, and a harmonious blend of natural and man-made beauty, Santorini captivates the hearts of travelers from around the world.',
        'https://images.unsplash.com/photo-1563789031959-4c02bcb41319?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80'),
       ('Belgrade', 'Serbia', 2000000.0,
        'Belgrade, the capital city of Serbia, is a captivating blend of history, culture, and vibrant energy. Situated at the confluence of the Sava and Danube rivers, it offers a rich tapestry of architectural styles, from the ancient Belgrade Fortress to the grandeur of the Orthodox churches and Ottoman heritage. The city''s bustling streets are filled with a lively atmosphere, charming cafes, and bustling markets. Visitors can explore the historic neighborhoods of Skadarlija and Zemun, stroll along the Knez Mihailova Street, or enjoy the vibrant nightlife in the famous Savamala district. With its numerous parks, such as Kalemegdan Park and Ada Ciganlija, Belgrade provides ample opportunities for outdoor activities and relaxation. Whether you''re interested in history, culture, or nightlife, Belgrade has something to offer every visitor, leaving a lasting impression of its unique charm.',
        'https://images.unsplash.com/photo-1630610857799-36b59ff3412e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1115&q=80'),
       ('Los Angeles', 'USA', 4000000.0,
        'Los Angeles, often referred to as LA, is a vibrant and iconic city located in Southern California, USA. It is known for its glitz, glamour, and entertainment industry, making it a global hub for film, television, and music. Los Angeles is home to Hollywood, where many of the world''s biggest movies and TV shows are produced. LA is also famous for its beautiful beaches, such as Santa Monica and Venice Beach. Nature enthusiasts can explore the nearby natural wonders, including the stunning Santa Monica Mountains and Griffith Park, which offers breathtaking views of the city from the iconic Griffith Observatory. Additionally, Los Angeles is home to several iconic landmarks, including the Hollywood Sign, Walk of Fame, and Rodeo Drive, known for its luxury shopping. Los Angeles captures the essence of the American dream and continues to attract dreamers and visitors from around the world.',
        'https://images.unsplash.com/photo-1429554429301-1c7d5ae2d42e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80'),
       ('Rio de Janeiro', 'Brazil', 6750000.0,
        'Rio de Janeiro is one of the most famous cities in Brazil and a top tourist destination worldwide. Known for its stunning natural beauty, vibrant culture, music, and lively atmosphere, Rio de Janeiro attracts millions of visitors from around the globe each year. The city is situated on the coast of the Atlantic Ocean, with beautiful sandy beaches like Copacabana and Ipanema that have become iconic worldwide. In addition to the beaches, Rio is home to the iconic statue of Christ the Redeemer, perched atop Corcovado Mountain, offering breathtaking views of the city. Rio is also renowned for its carnival atmosphere and the grand Carnival in Rio, one of the largest and most colorful carnivals in the world. In Rio de Janeiro, you''ll experience a fusion of breathtaking nature, lively culture, and warm hospitality, making it an unmissable destination for travelers worldwide.',
        'https://images.unsplash.com/photo-1552428386-840770ff7588?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1173&q=80');